import { type SketchConfig } from "../sketchConfig";

export const botConfig: Partial<SketchConfig> = {
  aimbot: "silent",
  aimbotEnabled: false,
  bot: true,
  botCrouch: false,
  botAim: false,
  wallbangs: false,
  fovCheck: false,
  aimKey: -1,
  aimReactionTime: 0,
  smoothFactor: 0,
  drawFOV: false,
  targetOnAimKey: false,
  bhop: true,
  autoSlide: false,
  rampAccel: true,
  slidehop: true,
  wallJump: true,
  nametags: true,
  newNametags: true,
  boxes: false,
  chams: true,
  overlayOpacity: 1,
  chamsOpacity: 0.7,
  tracers: true,
  forceAuto: true,
  recoilControl: false,
  recoilControlKey: -1,
  recoilSmoothFactor: 0.4,
  triggerbot: false,
  triggerbotKey: -1,
  triggerbotMin: 0,
  triggerbotMax: 0,
  noAdsFovMlt: true,
  multiPoint: true,
  multiPointScale: 0.5,
  skinHack: true,
  keybindOverlay: false,
  healthBars: true,
  thirdPerson: true,
  spinbot: "off",
  vibrator: true,
  autoSpawn: true,
};
